# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [2]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def multiply(t,matrix):
    """
        Determination of the number of inversions in each permutation.
        Multiplication of the corresponding elements of the matrix.
        Defining the mark.

    """
    list_res = []
    for j in t:
        factor_result = j
        k = 0
        res = 1
        n = 0
        factor_result = [int(x) for x in factor_result]
        factor_len = len(factor_result)
        # print(factor_len)
        for i in factor_result:
            for j in factor_result:
                # print(i, '  ', j)
                if i > j and factor_result.index(i) < factor_result.index(j):
                    k += 1
        for i in factor_result:
            #print(matrix[n, i - 1])
            res = res * matrix[n, i - 1]
            n += 1

        res = res * ((-1) ** k)
        #print(res)
        list_res.append(res)
    #print(list_res)
    return list_res



def sum(list_res):
    """
    Sum of all elements received from the multiply
    function
    """
    a = 0
    for i in list_res:
        a += i
    return a



while True:
     try:
         dim = int(input("Введіть розмірність матриці"))
         while dim <= 0 :
             print("Розмірність повинна задаватися додатнім числовм відмінним від 0.")
             dim = int(input("Введіть розмірність матриці"))
     except ValueError:   # Якщо тип данни - невірнй, програма незавершиться,
        print("Не коректні данні, дискрімінант менше 0")
        continue
     else:
        break


matrix = random_matrix(dim)

listt = list()
n = 0
while dim > 0:
    n += 1
    listt.append(str(n))
    dim -= 1

#Example of using permutations() method
t = list(itertools.permutations(listt, n))
#print(type(matrix))
#print(t)
print(matrix)
#print(matrix[0,0])
#print(matrix[1,1])
#print(matrix[2,2])


#print(multiply(t[0],matrix))
#print(multiply(t,matrix))
print("Взначник:",sum(multiply(t,matrix)))


[[2 8 6]
 [3 6 2]
 [5 1 3]]
Взначник: -122
